#!/bin/bash

CONTAINER_NAME="dev-env"
IMAGE_NAME="ubuntu:rolling"
HOST_PORT="9999"

docker stop $CONTAINER_NAME
docker build -t $IMAGE_NAME --build-arg MESSAGE="Message from build script" .
docker run -d --rm -p $HOST_PORT:80 --name $CONTAINER_NAME $IMAGE_NAME
# echo "Listening to localhost:$HOST_PORT, try http://localhost:$HOST_PORT"

echo "Build and run complete."