#!/bin/bash

CONTAINER_NAME="development-environment"
IMAGE_NAME="ubuntu:latest"
HOST_PORT="9999"

docker stop $CONTAINER_NAME
mkdir ./temp
cat ~/.ssh/id_rsa.pub > ./temp/id_rsa.pub
docker build -t $IMAGE_NAME --build-arg MESSAGE="Message from build script" --no-cache .
docker run -d --rm -p $HOST_PORT:80 --name $CONTAINER_NAME $IMAGE_NAME
rm -Rf ./temp
# echo "Listening to localhost:$HOST_PORT, try http://localhost:$HOST_PORT"

echo "Build and run complete."
